import { Nav } from '../components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '../components/Home/Footer'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='mx-auto w-11/12'>
      <Nav />

        {children}
        <Footer/>
        </body>
    </html>
  )
}
